version: "3.3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: yarn run dev
    stdin_open: true
    tty: true
    volumes:
      - ./client:/usr/src/app

