version: "3.3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: yarn run dev
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/usr/src/app/src

  dev:
    image: node:18-alpine
    container_name: app-client-container-dev
    volumes:
      - .:/usr/src/service/
    working_dir: /usr/src/service/
    command: sh -c "yarn install"

