query GalleryQuery {
  gallery(first: 4, after: "${lastItemId}") {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
    }
    nodes {
      id
      featuredImage {
        node {
          sourceUrl
        }
      }
      title
    }
  }
}